#! usr/bin/sh

./sim bimodal 7 0 0 traces/gcc_trace.txt >! my_runs/bimodal_1.txt
./sim bimodal 10 0 0 traces/gcc_trace.txt >! my_runs/bimodal_2.txt
./sim bimodal 6 0 0 traces/perl_trace.txt >! my_runs/bimodal_4.txt
./sim bimodal 5 0 0 traces/jpeg_trace.txt >! my_runs/bimodal_3.txt
./sim gshare 10 4 0 0 traces/gcc_trace.txt >! my_runs/gshare_1.txt
./sim gshare 14 9 0 0 traces/gcc_trace.txt >! my_runs/gshare_2.txt
./sim gshare 11 5 0 0 traces/jpeg_trace.txt >! my_runs/gshare_3.txt
./sim gshare 10 6 0 0 traces/perl_trace.txt >! my_runs/gshare_4.txt
./sim hybrid 9 14 11 6 0 0 traces/gcc_trace.txt >! my_runs/hybrid_1.txt
./sim hybrid 5 10 8 5 0 0 traces/jpeg_trace.txt >! my_runs/hybrid_2.txt

diff -iw my_runs/bimodal_1.txt val_runs/val_bimodal_1.txt
diff -iw my_runs/bimodal_2.txt val_runs/val_bimodal_2.txt
diff -iw my_runs/bimodal_3.txt val_runs/val_bimodal_3.txt
diff -iw my_runs/bimodal_4.txt val_runs/val_bimodal_4.txt
diff -iw my_runs/gshare_1.txt val_runs/val_gshare_1.txt
diff -iw my_runs/gshare_2.txt val_runs/val_gshare_2.txt
diff -iw my_runs/gshare_3.txt val_runs/val_gshare_3.txt
diff -iw my_runs/gshare_4.txt val_runs/val_gshare_4.txt
diff -iw my_runs/hybrid_1.txt val_runs/val_hybrid_1.txt
diff -iw my_runs/hybrid_2.txt val_runs/val_hybrid_2.txt
